### ISSUE TITLE
buff反爬虫

### ISSUE THREAD

**Issue by ccinv** [puppylpg/oddish#10]
使用默认配置（价格区间改为100-800，自己账号的cookie）
抓取途中出现一次：

> Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\oddish\src\__main__.py", line 13, in <module>
    table = item_crawler.crawl()
  File "D:\oddish\src\crawl\item_crawler.py", line 128, in crawl
    table = crawl_website()
  File "D:\oddish\src\crawl\item_crawler.py", line 75, in crawl_website
    enrich_item_with_price_history(csgo_items)
  File "D:\oddish\src\crawl\item_crawler.py", line 56, in enrich_item_with_price_history
    history_price_crawler.crawl_history_price(csgo_items)
  File "D:\oddish\src\crawl\history_price_crawler.py", line 34, in crawl_history_price
    crawl_item_history_price(index, item, total_price_number)
  File "D:\oddish\src\crawl\history_price_crawler.py", line 16, in crawl_item_history_price
    days = steam_history_prices['data']['days']
KeyError: 'data'

重新爬的时候返回：

>2020-07-26 15:49:02,258 [INFO ]  网站返回信息：
2020-07-26 15:49:02,258 [INFO ]  {'code': 'Action Forbidden', 'error': '市场接口访问功能暂时关闭，请稍后再试', 'extra': None}
2020-07-26 15:49:02,258 [INFO ]  错误为: 市场接口访问功能暂时关闭，请稍后再试

此时手动登入buff网页端和客户端也不能访问市场，说明buff是存在反爬虫的机制的。我在4月份的时候也跑了一次爬虫，没有什么问题，这可能是buff刚更新的？(；´д｀)ゞ
换IP后问题依然存在。我的账号不会被盯上了吧..

**Comment by puppylpg** [comment]
额，难道buff开始觉醒了=。=

不过这种应该也就封一会儿ip或者账号，停几个小时或者一两天应该就好了。
建议超时时间再调大一点儿 5-6s一次，爬的饰品范围设置小一些，应该就ok了
等回去我把超时参数自定义也加一下吧

**Comment by ccinv** [comment]
我用小号又试着跑了一遍。在获取历史价格时返回了
> {'code': 'Steam Binding Required', 'error': '未绑定Steam', 'extra': None}

这玩意还得绑定steam账号... 估计第一次在中途退出不是被buff ban了，而是返回的信息格式可能变了，你可以看一看。

**Comment by puppylpg** [comment]
https://github.com/puppylpg/oddish/releases/tag/v3.4.0 支持自定义时间了，可以调慢点儿，应该就不会账号冷却了
