### ISSUE TITLE
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by GeraltZeroZhong** [puppylpg/oddish#101]
# 问题描述
程序最开始出现错误
# 复现步骤
工程根目录下运行：`python -m src`
# 报错信息
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "F:\CS\oddish-master\oddish-master\src\__init__.py", line 41, in <module>
    ui = oddish(MainWindow)
  File "F:\CS\oddish-master\oddish-master\src\ui\oddish.py", line 96, in __init__
    self.priceMin.setValue(config.CRAWL_MIN_PRICE_ITEM)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
# 相关截屏（最好贴一下）

# 软件信息
- python版本：3.10
- 操作系统：win11

**Comment by Mackmomomo** [comment]
我也这样有什么方法可以解决吗
