### ISSUE TITLE
MAC 会有 raise URLError（err）报错

### ISSUE THREAD

**Issue by nxs333** [puppylpg/oddish#13]
MAC 会有 raise URLError（err）报错，用W10跑是正常的，cookie都检查了没有问题

**Comment by puppylpg** [comment]
> MAC 会有 raise URLError（err）报错，用W10跑是正常的，cookie都检查了没有问题

能完整贴一下报错信息吗，这个之前没碰到过

**Comment by nxs333** [comment]
今天MAC没带，但是跑了下W10也报错了，帮忙看下

**Comment by nxs333** [comment]
2020-08-18 02:56:25,521 [INFO ]  GET steam history price 1/375 for (鲍伊猎刀（★ StatTrak™） | 都市伪装 (久经沙场)): https://buff.163.com/api/market/goods/price_history?game=csgo&goods_id=43386&currency=&days=7
2020-08-18 02:56:25,521 [INFO ]  sleep 5s at 2020-08-18 02:56:25.521933
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\编程学习\untitled2\src\__main__.py", line 13, in <module>
    table = item_crawler.crawl()
  File "D:\编程学习\untitled2\src\crawl\item_crawler.py", line 128, in crawl
    table = crawl_website()
  File "D:\编程学习\untitled2\src\crawl\item_crawler.py", line 75, in crawl_website
    enrich_item_with_price_history(csgo_items)
  File "D:\编程学习\untitled2\src\crawl\item_crawler.py", line 56, in enrich_item_with_price_history
    history_price_crawler.crawl_history_price(csgo_items)
  File "D:\编程学习\untitled2\src\crawl\history_price_crawler.py", line 34, in crawl_history_price
    crawl_item_history_price(index, item, total_price_number)
  File "D:\编程学习\untitled2\src\crawl\history_price_crawler.py", line 16, in crawl_item_history_price
    days = steam_history_prices['data']['days']
KeyError: 'data'
