### ISSUE TITLE
运行时出现报错

### ISSUE THREAD

**Issue by a1234k5** [puppylpg/oddish#18]
2020-09-09 11:07:38,306 [INFO ]  sleep 7s at 2020-09-09 11:07:38.305014
Traceback (most recent call last):
  File "D:\Python3.8.5\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "D:\Python3.8.5\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "D:\Python3.8.5\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "D:\Python3.8.5\lib\site-packages\urllib3\connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "D:\Python3.8.5\lib\site-packages\urllib3\util\ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Python3.8.5\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Python3.8.5\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\Python3.8.5\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

**Comment by a1234k5** [comment]
2020-09-09 13:40:01,667 [INFO ]  sleep 2s at 2020-09-09 13:40:01.667368
Traceback (most recent call last):
  File "D:\Python3.8.5\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python3.8.5\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\oddish-master\src\__main__.py", line 13, in <module>
    table = item_crawler.crawl()
  File "D:\oddish-master\src\crawl\item_crawler.py", line 129, in crawl
    table = crawl_website()
  File "D:\oddish-master\src\crawl\item_crawler.py", line 76, in crawl_website
    enrich_item_with_price_history(csgo_items)
  File "D:\oddish-master\src\crawl\item_crawler.py", line 57, in enrich_item_with_price_history
    history_price_crawler.crawl_history_price(csgo_items)
  File "D:\oddish-master\src\crawl\history_price_crawler.py", line 41, in crawl_history_price
    crawl_item_history_price(index, item, total_price_number)
  File "D:\oddish-master\src\crawl\history_price_crawler.py", line 14, in crawl_item_history_price
    steam_history_prices = get_json_dict(steam_price_url, steam_cookies, True)
  File "D:\oddish-master\src\util\requester.py", line 36, in get_json_dict
    return requests.get(url, headers=headers, cookies=cookies, timeout=5, proxies=proxies, verify=False).json()
  File "D:\Python3.8.5\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Python3.8.5\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Python3.8.5\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python3.8.5\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by puppylpg** [comment]
看着也像是某一个请求和其他请求的返回不太一样，和 #16 一样处理了

**Comment by puppylpg** [comment]
https://github.com/puppylpg/oddish/releases/tag/v3.6.1
