### ISSUE TITLE
cookie问题无法登陆

### ISSUE THREAD

**Issue by XianUex** [puppylpg/oddish#19]
[log_2020-09-12-21_30.0_150.0.log](https://github.com/puppylpg/oddish/files/5212784/log_2020-09-12-21_30.0_150.0.log)
`buff_cookie = _ntes_nuid=4f15a67c4d23c6d5c5e36b7d5ea5f09c; mail_psc_fingerprint=4f3bd16e6925088bbd31d68fda3131e9; vinfo_n_f_l_n3=6b24a5b5acc2892e.1.2.1559471935727.1584932118066.1587630810278; Device-Id=Snh3bZoJYQOq1p9qWm0l; _ntes_nnid=4f15a67c4d23c6d5c5e36b7d5ea5f09c,1591192204495; __oc_uuid=07c42de0-d316-11ea-986c-0931c64ee96d; nts_mail_user=ajwswl69ip809@163.com:-1:1; Locale-Supported=zh-Hans; game=csgo; S_INFO=1599916336|0|3&80##|16602624571; P_INFO=16602624571|1599916336|1|netease_buff|00&99|null&null&null#tij&null#10#0|&0|null|16602624571; csrf_token=IjMyNmFmMWMyYjRjZWI0MjI1OWEyMTU5OTdjMzgzYmE1MjNkMzk2ZmUi.Ej5jow.Y4gl4ZJJylwOP9Zy4sAFWbgQs84
steam_cookie = timezoneOffset=28800,0; browserid=1991102511234804767; recentapps=%7B%221209000%22%3A1597726681%2C%221135830%22%3A1592827294%2C%22526870%22%3A1587128358%7D; sessionid=8657e31aefbea1e970e6d7c0; steamCountry=HK%7C93e762e5937328bccbed3a9c3422786a; steamRememberLogin=76561199027539030%7C%7Cc87590468274be055b7535c9f092edd0; deep_dive_carousel_method=default; deep_dive_carousel_focused_app=427520; app_impressions=1119700@1_4_4__100_1|632300@1_4_4__128_2`

复制cookie过来运行无法登陆，这个buff的cookie似乎和示例不太一样，但我从控制台中用多种办法也找不到更完整的cookie了，反复尝试无果，求教。

**Comment by puppylpg** [comment]
从cookie来看，感觉这并不是网页buff登陆之后的cookie。
1. 确定网页buff登陆了吗？
2. 登陆之后，从开发者工具里的Network栏，找到一个buff的请求，查看它的cookie，粘过来就行了。具体可以百度cookie如何复制，教程挺多的。

**Comment by wwp8898** [comment]
老哥 启动报错了 不知道是什么问题 
#python -m src        
2020-09-14 17:29:39,541 [INFO ]  Start Time: 2020-09-14 17:29:39.541335
2020-09-14 17:29:39,541 [INFO ]  Force crawling? False
2020-09-14 17:29:39,542 [INFO ]  Price section specified, crawl price between 100.0 and 200.0
2020-09-14 17:29:39,543 [INFO ]  GET: https://buff.163.com/market/?game=csgo#tab=selling&page_num=1
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/wuweipeng/oddish/src/__main__.py", line 13, in <module>
    table = item_crawler.crawl()
  File "/Users/wuweipeng/oddish/src/crawl/item_crawler.py", line 129, in crawl
    table = crawl_website()
  File "/Users/wuweipeng/oddish/src/crawl/item_crawler.py", line 64, in crawl_website
    raw_categories = csgo_all_categories()
  File "/Users/wuweipeng/oddish/src/crawl/item_crawler.py", line 44, in csgo_all_categories
    root_html = http_util.open_url(root_url)
  File "/Users/wuweipeng/oddish/src/util/http_util.py", line 5, in open_url
    page = urllib.request.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

**Comment by XianUex** [comment]
![51AWL QLY`$ O)H$%)B3T88](https://user-images.githubusercontent.com/47709634/93092448-f4bc6e00-f68e-11ea-97e1-ef01be1089fa.png)
从这里复制的cookie依然是这样的

**Comment by puppylpg** [comment]
神奇啊，你点“进入市场”之后看看cookie长啥样。不该这样啊

**Comment by XianUex** [comment]
![8HGYED@`88C56WXO96{@RU5](https://user-images.githubusercontent.com/47709634/93165545-de082c80-f70b-11ea-8921-68bca4eabbbd.png)

**Comment by puppylpg** [comment]
这个cookie也不行吗

**Comment by XianUex** [comment]
是的 也不行

**Comment by puppylpg** [comment]
哦，我知道了……你是不是把buff_cookie和steam_cookie放在同一行了……他们应该是两行

**Comment by XianUex** [comment]
![D$N U63F8C`QMMKQKY0DUJX](https://user-images.githubusercontent.com/47709634/93166189-794dd180-f70d-11ea-902f-fb045fe1de7e.png)
我是这样放的

**Comment by puppylpg** [comment]
格式看着是没问题了。要不你多换几个浏览器，看看别的浏览器登陆后的cookie拷出来能不能用。可能chrome有什么插件之类的影响了cookie

**Comment by XianUex** [comment]
NameError: name 'COOKIE' is not defined 
输出最后一行发现这个...

**Comment by puppylpg** [comment]
代码是最新的吗……

**Comment by XianUex** [comment]
3.6.1 和直接下载的压缩包...都这样

**Comment by puppylpg** [comment]
如果换浏览器也不行……那只能换电脑了 :D
:sob:
