### ISSUE TITLE
老哥 启动报错 但是不知道是什么问题

### ISSUE THREAD

**Issue by wwp8898** [puppylpg/oddish#20]
wuweipeng@localhost oddish % python -m src        
2020-09-14 17:29:39,541 [INFO ]  Start Time: 2020-09-14 17:29:39.541335
2020-09-14 17:29:39,541 [INFO ]  Force crawling? False
2020-09-14 17:29:39,542 [INFO ]  Price section specified, crawl price between 100.0 and 200.0
2020-09-14 17:29:39,543 [INFO ]  GET: https://buff.163.com/market/?game=csgo#tab=selling&page_num=1
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/wuweipeng/oddish/src/__main__.py", line 13, in <module>
    table = item_crawler.crawl()
  File "/Users/wuweipeng/oddish/src/crawl/item_crawler.py", line 129, in crawl
    table = crawl_website()
  File "/Users/wuweipeng/oddish/src/crawl/item_crawler.py", line 64, in crawl_website
    raw_categories = csgo_all_categories()
  File "/Users/wuweipeng/oddish/src/crawl/item_crawler.py", line 44, in csgo_all_categories
    root_html = http_util.open_url(root_url)
  File "/Users/wuweipeng/oddish/src/util/http_util.py", line 5, in open_url
    page = urllib.request.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

**Comment by puppylpg** [comment]
https://stackoverflow.com/a/53310545/7676237

**Comment by puppylpg** [comment]
> https://stackoverflow.com/a/53310545/7676237

看起来是mac的问题，你可以探究一下 :D

**Comment by wwp8898** [comment]
> > https://stackoverflow.com/a/53310545/7676237
> 
> 看起来是mac的问题，你可以探究一下：D

老哥 是我环境的问题 
2020-09-14 17:53:40,382 [INFO ]  Finish parsing AWP | 野火 (破损不堪).
2020-09-14 17:53:40,383 [INFO ]  Finish parsing AWP | 黑色魅影 (略有磨损).
2020-09-14 17:53:40,384 [INFO ]  Finish parsing AWP | *嘣* (略有磨损).
2020-09-14 17:53:40,384 [INFO ]  Finish parsing AWP（纪念品） | 粉红 DDPAT (战痕累累).
2020-09-14 17:53:40,384 [INFO ]  Finish parsing AWP | 冲出重围 (破损不堪).
2020-09-14 17:53:40,384 [INFO ]  Finish parsing AWP（StatTrak™） | 电子蜂巢 (久经沙场).
2020-09-14 17:53:40,385 [INFO ]  Finish parsing AWP | 红线 (略有磨损).
2020-09-14 17:53:40,386 [INFO ]  Finish parsing AWP（StatTrak™） | 浮生如梦 (崭新出厂).
2020-09-14 17:53:40,387 [INFO ]  Finish parsing AWP（纪念品） | 粉红 DDPAT (破损不堪).
2020-09-14 17:53:40,387 [INFO ]  Finish parsing AWP（StatTrak™） | 树蝰 (崭新出厂).
2020-09-14 17:53:40,387 [INFO ]  Finish parsing AWP | 黑色魅影 (久经沙场).
2020-09-14 17:53:40,388 [INFO ]  Finish parsing AWP（纪念品） | 粉红 DDPAT (久经沙场).
2020-09-14 17:53:40,388 [INFO ]  Finish parsing AWP | *嘣* (久经沙场).
2020-09-14 17:53:40,388 [INFO ]  Finish parsing AWP | 红线 (破损不堪).
2020-09-14 17:53:40,388 [INFO ]  Finish parsing AWP（纪念品） | 冥界之河 (战痕累累).
2020-09-14 17:53:40,388 [INFO ]  Finish parsing AWP（StatTrak™） | 精英之作 (略有磨损).
2020-09-14 17:53:40,388 [INFO ]  Finish parsing AWP | 黑色魅影 (破损不堪).
2020-09-14 17:53:40,388 [INFO ]  Finish parsing AWP | 电子蜂巢 (崭新出厂).
2020-09-14 17:53:40,389 [INFO ]  Finish parsing AWP | 暴怒野兽 (久经沙场).
2020-09-14 17:53:40,389 [INFO ]  Finish parsing AWP | 冲出重围 (战痕累累).
2020-09-14 17:53:40,389 [INFO ]  Page 2 / 2
2020-09-14 17:53:40,389 [INFO ]  sleep 4s at 2020-09-14 17:53:40.389346
2020-09-14 17:53:48,592 [INFO ]  Finish parsing AWP | 野火 (战痕累累).
2020-09-14 17:53:48,593 [INFO ]  Finish parsing AWP | 黑色魅影 (战痕累累).
2020-09-14 17:53:48,593 [INFO ]  Finish parsing AWP（StatTrak™） | 珊瑚树 (略有磨损).
2020-09-14 17:53:48,593 [INFO ]  Finish parsing AWP | 电子蜂巢 (破损不堪).
2020-09-14 17:53:48,593 [INFO ]  Finish parsing AWP | 珊瑚树 (崭新出厂).
2020-09-14 17:53:48,593 [INFO ]  Finish parsing AWP（StatTrak™） | 珊瑚树 (久经沙场).
2020-09-14 17:53:48,594 [INFO ]  Finish parsing AWP | 粉红 DDPAT (略有磨损).
2020-09-14 17:53:48,594 [INFO ]  Finish parsing AWP（纪念品） | 冥界之河 (久经沙场).
2020-09-14 17:53:48,594 [INFO ]  Finish parsing AWP | 暴怒野兽 (破损不堪).
2020-09-14 17:53:48,594 [INFO ]  Finish parsing AWP | 红线 (久经沙场).
2020-09-14 17:53:48,594 [INFO ]  Finish parsing AWP（StatTrak™） | 死神 (崭新出厂).
2020-09-14 17:53:48,595 [INFO ]  GET: https://buff.163.com/api/market/goods?game=csgo&page_num=9223372036854775807&sort_by=price.asc&min_price=100.0&max_price=200.0&category=weapon_ak47
2020-09-14 17:53:48,595 [INFO ]  sleep 3s at 2020-09-14 17:53:48.595193

应该是工作了吧

**Comment by puppylpg** [comment]
:+1:

**Comment by y-j** [comment]
> wuweipeng@localhost oddish % python -m src
> 2020-09-14 17:29:39,541 [INFO ] Start Time: 2020-09-14 17:29:39.541335
> 2020-09-14 17:29:39,541 [INFO ] Force crawling? False
> 2020-09-14 17:29:39,542 [INFO ] Price section specified, crawl price between 100.0 and 200.0
> 2020-09-14 17:29:39,543 [INFO ] GET: https://buff.163.com/market/?game=csgo#tab=selling&page_num=1
> Traceback (most recent call last):
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1319, in do_open
> h.request(req.get_method(), req.selector, req.data, headers,
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
> self._send_request(method, url, body, headers, encode_chunked)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
> self.endheaders(body, encode_chunked=encode_chunked)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
> self._send_output(message_body, encode_chunked=encode_chunked)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1004, in _send_output
> self.send(msg)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 944, in send
> self.connect()
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1399, in connect
> self.sock = self._context.wrap_socket(self.sock,
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
> return self.sslsocket_class._create(
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
> self.do_handshake()
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
> self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
> return _run_code(code, main_globals, None,
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
> exec(code, run_globals)
> File "/Users/wuweipeng/oddish/src/**main**.py", line 13, in
> table = item_crawler.crawl()
> File "/Users/wuweipeng/oddish/src/crawl/item_crawler.py", line 129, in crawl
> table = crawl_website()
> File "/Users/wuweipeng/oddish/src/crawl/item_crawler.py", line 64, in crawl_website
> raw_categories = csgo_all_categories()
> File "/Users/wuweipeng/oddish/src/crawl/item_crawler.py", line 44, in csgo_all_categories
> root_html = http_util.open_url(root_url)
> File "/Users/wuweipeng/oddish/src/util/http_util.py", line 5, in open_url
> page = urllib.request.urlopen(url)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
> return opener.open(url, data, timeout)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
> response = self._open(req, data)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
> result = self._call_chain(self.handle_open, protocol, protocol +
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
> result = func(*args)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1362, in https_open
> return self.do_open(http.client.HTTPSConnection, req,
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1322, in do_open
> raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
你好，我也出现了这个问题，你是怎么解决的？

**Comment by y-j** [comment]
你好，我的mac也出现了这个问题，你是怎么解决的？
