### ISSUE TITLE
ConnectionRefusedError: [WinError 10061]由于目标计算机积极拒绝,无法连接

### ISSUE THREAD

**Issue by jjd-1228** [puppylpg/oddish#33]
# 问题描述
应该是在爬steam市场的时候出的错吧。。

Traceback (most recent call last):
  File "D:\MyGitHub\oddish\src\util\requester.py", line 48, in get_json_dict_raw
    return requests.get(url, headers = headers, cookies = cookies, timeout = 5, proxies = proxies).text
  File "C:\Users\Jin\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Jin\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Jin\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Jin\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Jin\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='steamcommunity.com', port=443): Max retries exceeded with url: /market/pricehistory/?country=CN&currency=1&appid=730&market_hash_name=M4A1-S%20%7C%20Golden%20Coil%20%28Minimal%20Wear%29 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0D6B19E8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by puppylpg** [comment]
代码版本之类的给一下吧，要不然很难确定问题啊。根据报错信息，看起来是代理配置的有问题

**Comment by puppylpg** [comment]
可以看一下 #34 

爬的时候代理出了问题，连不上代理了。
