### ISSUE TITLE
控制台报错，无法运行，老哥过来帮忙看看

### ISSUE THREAD

**Issue by kongxianzzz** [puppylpg/oddish#4]
`Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\3D Objects\OneDrive - student.cumtb.edu.cn\桌面\oddish-master\src\__main__.py", line 3, in <module>
    from src.crawl import item_crawler
  File "C:\Users\admin\3D Objects\OneDrive - student.cumtb.edu.cn\桌面\oddish-master\src\crawl\item_crawler.py", line 3, in <module>
    from src.config.definitions import *
  File "C:\Users\admin\3D Objects\OneDrive - student.cumtb.edu.cn\桌面\oddish-master\src\config\definitions.py", line 15, in <module>
    config.read(CONFIG_PATH, encoding='utf-8')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 1079, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\admin\\3D Objects\\OneDrive - student.cumtb.edu.cn\\桌面\\oddish-master\\config\\config.ini', line: 1
'\ufeffSIC]\n'

1. 网上搜了一下，说是编码问题，但我改了几次都不行鸭，大佬能解决一下吗

`

**Comment by puppylpg** [comment]
是不是用记事本编辑保存了=。=
建议下载一个notepad++，记事本保存会默认加BOM之类的，编码不对

**Comment by kongxianzzz** [comment]
好的已经解决了，就是记事本的问题
