### ISSUE TITLE
为啥出现了这个代码

### ISSUE THREAD

**Issue by 1105949368** [puppylpg/oddish#7]
2020-06-19 13:11:01,153 [INFO ]  sleep 2s at 2020-06-19 13:11:01.153047
Traceback (most recent call last):
  File "D:\Program Files\python3.7\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "D:\Program Files\python3.7\lib\site-packages\urllib3\connectionpool.py", line 930, in _prepare_proxy
    conn.connect()
  File "D:\Program Files\python3.7\lib\site-packages\urllib3\connection.py", line 316, in connect
    self._tunnel()
  File "D:\Program Files\python3.7\lib\http\client.py", line 906, in _tunnel
    (version, code, message) = response._read_status()
  File "D:\Program Files\python3.7\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Program Files\python3.7\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\python3.7\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Program Files\python3.7\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Program Files\python3.7\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='buff.163.com', port=443): Max retries exceeded with url: /api/market/goods/price_history?game=csgo&goods_id=43599&currency=&d
ays=7 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\python3.7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files\python3.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\王城城\Desktop\oddish-master\src\__main__.py", line 13, in <module>
    table = item_crawler.crawl()
  File "C:\Users\王城城\Desktop\oddish-master\src\crawl\item_crawler.py", line 128, in crawl
    table = crawl_website()
  File "C:\Users\王城城\Desktop\oddish-master\src\crawl\item_crawler.py", line 75, in crawl_website
    enrich_item_with_price_history(csgo_items)
  File "C:\Users\王城城\Desktop\oddish-master\src\crawl\item_crawler.py", line 56, in enrich_item_with_price_history
    history_price_crawler.crawl_history_price(csgo_items)
  File "C:\Users\王城城\Desktop\oddish-master\src\crawl\history_price_crawler.py", line 34, in crawl_history_price
    crawl_item_history_price(index, item, total_price_number)
  File "C:\Users\王城城\Desktop\oddish-master\src\crawl\history_price_crawler.py", line 13, in crawl_item_history_price
    steam_history_prices = requester.get_json_dict(steam_price_url)
  File "C:\Users\王城城\Desktop\oddish-master\src\util\requester.py", line 27, in get_json_dict
    return requests.get(url, headers=headers, cookies=cookies, timeout=5).json()
  File "D:\Program Files\python3.7\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Program Files\python3.7\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Program Files\python3.7\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Program Files\python3.7\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "D:\Program Files\python3.7\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='buff.163.com', port=443): Max retries exceeded with url: /api/market/goods/price_history?game=csgo&goods_id=43599&currency=&day
s=7 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))

**Comment by puppylpg** [comment]
是不是网的问题，连不上buff的网站，重试了好几次也不行，就凉了
