### ISSUE TITLE
请问4.1.0版本安装了aiosocks一直显示ModuleNotFoundError: No module named 'aiohttp_socks'是怎么回事

### ISSUE THREAD

**Issue by angusleee** [puppylpg/oddish#73]
如题，aiosocks是输入pip install aiosocks安装的（但自动安装版本并不是您推荐的0.5.5而是0.2.6，作为小白也不知道发生了什么）
然后在输入python -m src的过程中就会出现以下字样：
>python -m src
Traceback (most recent call last):
  File "D:\anaconda3\envs\new\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\new\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Rico\oddish-4.1.0\src\__main__.py", line 3, in <module>
    from src.crawl import item_crawler
  File "C:\Users\Rico\oddish-4.1.0\src\crawl\item_crawler.py", line 9, in <module>
    from src.crawl import history_price_crawler
  File "C:\Users\Rico\oddish-4.1.0\src\crawl\history_price_crawler.py", line 9, in <module>
    from aiohttp_socks import ProxyConnector
ModuleNotFoundError: No module named 'aiohttp_socks'
然后就被强行终止了。

具体情况就是这样，打扰您啦。

**Comment by puppylpg** [comment]
要不试试`pip install aiosocks==0.5.5`，具体不清楚，可能是版本低的原因

实在搞不定也可以试试v3.9.3，不需要安装这个，就是爬的慢点儿

**Comment by angusleee** [comment]
好的，谢谢您，我再试试

**Comment by HappyWangzy** [comment]
代码留错了 应为pip install aiohttp_socks

**Comment by puppylpg** [comment]
> 代码留错了 应为pip install aiohttp_socks

QAQ 已修正
