### ISSUE TITLE
请问[Error 22] 远程计算机拒绝网络连接 如何解决

### ISSUE THREAD

**Issue by SaIvare000** [puppylpg/oddish#80]
# 问题描述
我挂了buff，没有改proxy，一开始还可以，爬了好一会后就成这样了，这个是什么问题？
# 复现步骤

# 报错信息
Traceback (most recent call last):
  File "C:\Users\Administrator\oddish-master\src\util\requester.py", line 101, in async_get_json_dict_raw
    async with session.get(url) as resp:
  File "D:\Program Files (x86)\anaconda\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "D:\Program Files (x86)\anaconda\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "D:\Program Files (x86)\anaconda\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\Program Files (x86)\anaconda\lib\site-packages\aiohttp\connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\Program Files (x86)\anaconda\lib\site-packages\aiohttp\connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\Program Files (x86)\anaconda\lib\site-packages\aiohttp_socks\connector.py", line 58, in _wrap_create_connection
    stream = await proxy.connect(
  File "D:\Program Files (x86)\anaconda\lib\site-packages\python_socks\async_\asyncio\ext\_proxy.py", line 47, in connect
    await self._connect()
  File "D:\Program Files (x86)\anaconda\lib\site-packages\python_socks\async_\asyncio\ext\_proxy.py", line 73, in _connect
    raise ProxyConnectionError(e.errno, msg) from e
python_socks._errors.ProxyConnectionError: [Errno 22] Can not connect to proxy 127.0.0.1:10808 [远程计算机拒绝网络连接。]
# 相关截屏（最好贴一下）

# 软件信息
请完善以下信息：
- python版本：3.9.1
- oddish版本（tag或者commit id）：v4.1.0

- 操作系统：Windows 10；

**Comment by Awol-a** [comment]
端口有问题，你用uu加速器试试，别忘把proxy留空
