### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by HooinIcecream** [puppylpg/oddish#97]
(buff) E:\buff>python -m src
Traceback (most recent call last):
  File "E:\buff\src\ui\oddish.py", line 28, in run
    table = item_crawler.crawl()
  File "E:\buff\src\crawl\item_crawler.py", line 167, in crawl
    t = asyncio.run(crawl_goods_by_price_section(category))
  File "D:\python\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "D:\python\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "E:\buff\src\crawl\item_crawler.py", line 95, in crawl_goods_by_price_section
    if 'data' not in root_json:
TypeError: argument of type 'NoneType' is not iterable
有谁知道怎么解决吗

**Comment by bromine2** [comment]
请问现在问题解决了吗？

**Comment by FengZhiheng** [comment]
遇到了相同问题
